### ISSUE TITLE
No code :)

### ISSUE THREAD

**Issue by roachspray** [utwente-fmt/llmc#1]
I am curious if LLMC will ever be made open? Thank you

**Comment by alaarman** [comment]
Thanks for your interest.
An unofficial version was available online for a while, so I can share it with you:
[llmc-0.1.zip](https://github.com/utwente-fmt/llmc/files/167025/llmc-0.1.zip)
For details see the thesis of @bergfi:
http://fmt.cs.utwente.nl/education/master/190/

**Comment by roachspray** [comment]
@alaarman Thank you for the help! I appreciate it. It is interesting work, to me, so just wanting to "play." Cheers!

**Comment by alaarman** [comment]
You are welcome.
LLMC is somehwat limited, but supports weak memory semantics.

For a mature model checking solution of LLVM, I suggest you take a look at Divine 3, which has excellent LLVM library support (though it does not support weak memory semantics directly, only by translation).
https://divine.fi.muni.cz/index.html

**Comment by roachspray** [comment]
Ah this is neat; I actually had not heard of this before. I appreciate the pointer!
